import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kasar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center flex-grow overflow-y-scroll font-body">
        <h1 className="flex flex-col items-end mt-10">
          <span className="text-4xl font-logo-light">Bienvenue sur</span>
          <span className="text-transparent text-7xl font-logo bg-clip-text bg-gradient-to-r from-primary to-secondary">Kasar</span>
        </h1>
      </main>
    </>
  );
}
