import Head from "next/head";
import Image from "next/image";
import { Header } from "./../components/Header/index";
import { Footer } from "./../components/Footer/index";
import Parser from "rss-parser";

export default function Home(podcasts) {
  podcasts = podcasts.podcasts;
  console.log(podcasts);
  podcasts?.items?.forEach((item) => {
    console.log(item.title + ":" + item.link);
  });
  return (
    <>
      <Head>
        <title>Kasar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-col items-center flex-grow overflow-y-scroll font-body">
        <h1 className="flex flex-col items-end">
          <span className="text-4xl font-logo-light">Bienvenue à</span>
          <span className="text-6xl font-logo text-primary">Kasar</span>
        </h1>
      </main>

      <Footer />
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const parser = new Parser();
  const podcasts = await parser.parseURL("http://136.243.117.30:8000/").then((data) => {
    return data === undefined ? null : data;
  });
  return {
    props: {
      podcasts: { ...podcasts },
    },
  };
};
